variables:
  MAVEN_CLI_OPTS: '--batch-mode'
  MAVEN_OPTS: '-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository'

.default-job-settings:
  tags:
    - java

stages:
  - build
  - deploy

build:
  extends: .default-job-settings
  stage: build
  script:
    - ln -svf /usr/local/jdk-17/bin/* /usr/bin/
    - |-
      set -x
      for t in check build; do
          sh gradlew --console plain "$t" \
            || { \
                  tar --show-transformed-names --transform="s@^build/reports/tests/test@test_report@" -cvf - build/reports/tests/test/* | xz -1 > test-report-${CI_COMMIT_REF_SLUG}.tar.xz; \
                  sh gradlew --console plain --info "$t"; \
                  exit 1; \
               }
      done
      set +x
    - 'tar --show-transformed-names --transform="s@^build/libs/@@;s@^build/resources/main/external/@@;" -cvf - build/libs/*.jar build/resources/main/external/* | xz -1 > user-profile-api-${CI_COMMIT_REF_SLUG}.tar.xz'
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' build/jacoco.csv
  artifacts:
    when: always
    name: user-profile-api-$CI_COMMIT_REF_SLUG
    paths:
      - '*.tar.xz'
      - 'keycloak-user-spi/build/libs/keycloak-user-spi.jar'
    reports:
      junit: build/test-results/test/TEST-*.xml

deploy-spi-plugin-dev-and-test:
  tags:
    - kontur
    - ansible
  stage: deploy
  when: manual
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  variables:
    METADATA_FILE_NAME: "keycloak01-artifacts.txt"
    SOURCE_JAR_PATH: "keycloak-user-spi/build/libs/keycloak-user-spi.jar"
  script:
    - echo 'source file:'
    - ls -l $SOURCE_JAR_PATH
    - SHA=`shasum -a 256 $SOURCE_JAR_PATH | awk '{print $1}'`
    - echo 'SHA='$SHA
    - DATE=`date -ur $SOURCE_JAR_PATH "+%Y%m%d%H%M.%S"`
    - sed -i 's!sha256!'$SHA'!g' keycloak-user-spi/$METADATA_FILE_NAME
    - sed -i 's!datetime!'$DATE'!g' keycloak-user-spi/$METADATA_FILE_NAME
    - aws s3 cp keycloak-user-spi/$METADATA_FILE_NAME s3://user-profile-service-locker01/DEV/$METADATA_FILE_NAME --sse
    - aws s3 cp keycloak-user-spi/$METADATA_FILE_NAME s3://user-profile-service-locker01/TEST/$METADATA_FILE_NAME --sse
    - aws s3 cp --content-type='text/plain' $SOURCE_JAR_PATH s3://user-profile-service-locker01/DEV/keycloak-user-spi.jar --sse
    - aws s3 cp --content-type='text/plain' $SOURCE_JAR_PATH s3://user-profile-service-locker01/TEST/keycloak-user-spi.jar --sse
  dependencies:
    - build

deploy-dev:
  tags:
    - kontur
    - ansible
  stage: deploy
  script: >
    ansible-playbook -vD -e "version=$CI_COMMIT_REF_SLUG-$CI_PIPELINE_IID
    path_to_dist=$(find $CI_PROJECT_DIR -maxdepth 1 -name user-profile-api\*.tar.xz -print -quit)"
    --limit=zigzag_user_profile_api ansible/deploy.yml
  environment:
    name: 'DEV'
    url: 'https://test-apps02.konturlabs.com/userprofile/'
  when: manual
  dependencies:
    - build

deploy-test:
  tags:
    - kontur
    - ansible
  stage: deploy
  script: >
    ansible-playbook -vD -e "version=$CI_COMMIT_REF_SLUG-$CI_PIPELINE_IID
    path_to_dist=$(find $CI_PROJECT_DIR -maxdepth 1 -name user-profile-api\*.tar.xz -print -quit)"
    --limit=sonic_user_profile_api ansible/deploy.yml
  environment:
    name: 'TEST'
    url: 'https://test-apps.konturlabs.com/userprofile/'
  when: manual
  dependencies:
    - build

deploy-spi-plugin-prod:
  tags:
    - kontur
    - ansible
  stage: deploy
  only:
    - /^release-.*$/
  when: manual
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  variables:
    METADATA_FILE_NAME: "keycloak01-artifacts.txt"
    SOURCE_JAR_PATH: "keycloak-user-spi/build/libs/keycloak-user-spi.jar"
  script:
    - echo 'source file:'
    - ls -l $SOURCE_JAR_PATH
    - SHA=`shasum -a 256 $SOURCE_JAR_PATH | awk '{print $1}'`
    - echo 'SHA='$SHA
    - DATE=`date -ur $SOURCE_JAR_PATH "+%Y%m%d%H%M.%S"`
    - sed -i 's!sha256!'$SHA'!g' keycloak-user-spi/$METADATA_FILE_NAME
    - sed -i 's!datetime!'$DATE'!g' keycloak-user-spi/$METADATA_FILE_NAME
    - aws s3 cp keycloak-user-spi/$METADATA_FILE_NAME s3://user-profile-service-locker01/PROD/$METADATA_FILE_NAME --sse
    - aws s3 cp $SOURCE_JAR_PATH s3://user-profile-service-locker01/PROD/keycloak-user-spi.jar --sse
  dependencies:
    - build

deploy-prod:
  tags:
    - kontur
    - ansible
  stage: deploy
  script: >
    ansible-playbook -vD -e "version=$CI_COMMIT_REF_SLUG-$CI_PIPELINE_IID
    path_to_dist=$(find $CI_PROJECT_DIR -maxdepth 1 -name user-profile-api\*.tar.xz -print -quit)"
    --limit=lima_user_profile_api ansible/deploy.yml
  environment:
    name: 'PROD'
    url: 'https://apps.kontur.io/userprofile/'
  only:
    - /^release-.*$/
  when: manual
  dependencies:
    - build
