server:
  port: 8631
  servlet:
    context-path: /userprofile

spring:
  liquibase:
    changelog: classpath:changelog/changelog.yaml
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/userprofile
    password: user-profile-api
    username: user-profile-api
    hikari:
      maximum-pool-size: 10
      minimum-idle: 3
      auto-commit: false
      driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak01.konturlabs.com/auth/realms/dev
          jwk-set-uri: https://keycloak01.konturlabs.com/auth/realms/dev/protocol/openid-connect/certs
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
    hibernate:
      ddl-auto: none #none so that Hibernate doesn't update schema (this is already done by liquibase)
      use-new-id-generator-mappings: false #false means use postgres sequences
    open-in-view: false

springdoc:
  writer-with-default-pretty-printer: true