server:
  port: 8631
  servlet:
    context-path: /userprofile
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  liquibase:
    changelog: classpath:changelog/changelog.yaml
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/userprofile
    password: user-profile-api
    username: user-profile-api
    hikari:
      maximum-pool-size: 10
      minimum-idle: 3
      auto-commit: false
      driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-keycloak.k8s-01.konturlabs.com/realms/dev
          jwk-set-uri: https://dev-keycloak.k8s-01.konturlabs.com/realms/dev/protocol/openid-connect/certs
  jpa:
    hibernate:
      dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
      ddl-auto: none #none so that Hibernate doesn't update schema (this is already done by liquibase)
      use-new-id-generator-mappings: false #false means use postgres sequences
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
      base-path: /
      path-mapping:
        prometheus: metrics

springdoc:
  writer-with-default-pretty-printer: true
  swagger-ui:
    path: 'doc'

sentry:
  dsn: https://fixme@dsn.ingest.sentry.io/project-id
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0

# Payment gateways config
payments:
  paypal:
    host: https://api.sandbox.paypal.com
    webhook-id: 2P781688HP282732G # sandbox
    client-id: AWJQJnM0O2nDEUgmMe9827bk73hjJdo3f4tPK9vwKvBVwFnDk1UGzk_Y2yeh5huiStwwdJVRmdOYWmhv
    client-secret: 1JE4291016473214C # this is fake, get the actual one from the PayPal dashboard
    connection-timeout: 10
    read-timeout: 30

intercom:
  enabled: false
  host: https://api.intercom.io
  token: example-token